config/routes.rb
Rails.application.routes.draw do

  resources :users

  get 'login' => 'sessions#new' unless @current_user
  get 'logout' => 'sessions#destroy'

  resources :sessions, only: [:new, :create, :destroy]
  resources :figures do
    member do
      patch :convert
    end
  end

  root 'welcome#index'

end

app/models/figure.rb
class Figure < ActiveRecord::Base


end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	validates_uniqueness_of :email
	
	validates_presence_of :name
	validates_presence_of :email

	#after_create :send_thankyou_email

	# def send_new_friend_to_all
	# 	UserMailer.new_friend_message_to_all(User.all, self)
	# end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :ensure_logged_in
  helper_method :current_user

  private

  # If the method coming from the view is 'delete', dont do anything and 
  #   let the delete method happen.
  # else find the user_id from the login/signup page and save to 
  #   the @current_user var
  def current_user
  	unless params['_method'] == "delete"
  		@current_user ||= User.find(session[:user_id]) if session[:user_id]
  	end
  end

  # Authenticates whether the user is logged in to the system.
  # Checks to make sure the 'current_user' method is set
  # If not, then the controller routes the user to the front page
  def ensure_logged_in
  	if current_user.nil?
  		redirect_to login_path
  	end
  end

end

app/controllers/figures_controller.rb
class FiguresController < ApplicationController

	# GET /index
	# grabs all figures out of the DB and sends to the view
	def index
		@figures = Figure.all
	end

	# PUT /figure/:id
	# finds the relative figure through the url params
	# toggles the 'converted pastafarian' column between true and false
	# redirects back to the view with json success/failure binary
	def update
		@figure = Figure.find(params[:id])
		if @figure.converted_pastafarian
			@figure.converted_pastafarian = false
			@figure.save
			respond_to do |format|
				format.json { render json: @figure.converted_pastafarian }
				format.html { redirect_to figures_path}
			end
		else
			@figure.converted_pastafarian = true
			@figure.save
			respond_to do |format|
				format.js { render json: @figure.converted_pastafarian }
				format.html { redirect_to figures_path}
			end
		end
	end
		# if @figure.update_attributes(figure_params)
		# 	respond_to do |format|
		# 		format.js { render plain: "1"}
		# 		format.html { redirect_to figures_path}
		# 	end
		# else
		# 	respond_to do |format|
		# 		format.js { render plain: "0"}
		# 		format.html {redirect_to figures_path, notice: "Conversion failed" }
		# 	end
		# end
		# else
		# 	@figure.converted_pastafarian = false
		# 	@figure.save
		# 	respond_to do |format|
		# 		format.js { render plain: "1"}
		# 		format.html { redirect_to figures_path}
		# 	end
		# end

	# DESTROY /figures/:id
	# receives id from the url params and deletes the record from the DB
	# In early stages of the app, the user could destroy the physical record of the 
	#   figure on the database.
	# now that everyone will have access to the DB, the javascript hides the view until
	#   page refresh
	def destroy
		@figure = Figure.find(params[:id])
		if @figure.destroy
			respond_to do |format|
				format.js { render plain: "1"}
				format.html { redirect_to figures_path}
			end
		else
			respond_to do |format|
				format.js { render plain: "0"}
				format.html {redirect_to tasks_path, notice: "SHUN failed" }
			end
		end
	end

	private

	# defines the params permitted by the 'def update' method
	def figure_params
		params.require(:figure).permit(:converted_pastafarian)
	end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	skip_filter :ensure_logged_in

	def create
		user = User.find_by_email(params[:email]).try(:authenticate, params[:password])
		if user
			session[:user_id] = user.id
			redirect_to figures_path, notice: "You've logged in."
		else
			flash.now.alert = "Your login attempt failed."
			render :new
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_path, notice: "You are now loggged out."
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	skip_filter :ensure_logged_in, only: [:new, :create, :destroy, :delete]
	def index
		@users = User.all
	end
	def new
		@new_user = User.new
	end
	def create
		@new_user = User.new(user_params)
		if @new_user.save
			UserMailer.new_friend_message(@new_user).deliver
			# flash[:notice] = "You Signed up successfully!"
			redirect_to user_path(@new_user)
		else
			# flash[:notice] = "bummer, something went wrong"
			render new_user_path
		end
	end
	def show
		@user = current_user # calling the helper method defined in the application controller
	end
	def user_params
		params.require(:user).permit(:name, :email, :password)
	end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	skip_filter :ensure_logged_in

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/figures/index.html.haml
.everything
	%nav.top-bar{"data-topbar" => ""}
		%section.top-bar-section
			/ Right Nav Section
			%ul.right
				%li
					%a{href: "#"}
						Logged in as 
						= current_user.name

				%li
					%a{href: logout_path} Logout
					
			
	.row
		.small-6.columns
		.small-6.columns
			%h3 Highly Religious Figures
			%table 
				%thead
					%th Name
					%th Converted Pastafarian?
					%th Has that changed?
					%th Shun the nonbeliever!
				%tbody{id: "happy-sunshine"}
				-@figures.each do |f|
					%tr
						%td= f.name
						%td{id: "bool"}= f.converted_pastafarian
							
						%td
							%button.button.tiny.success{ data: { "figure-id" => f.id}}
								Convert
							
						%td
							%button.button.tiny.alert{ data: { "figure-id" => f.id}}
								SHUN
							/ = link_to "SHUN", { action: "destroy", id: f.id}, data: { "figure-id" => f.id}, class: "button tiny alert", method: :delete
							/ %a.button.tiny.alert
							/ 	SHUN
							

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PostgresLoginApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_nav_bar.html.haml
%a= link_to "Logout", logout_path

app/views/users/edit.html.haml
= render 'nav_bar'
edit.html.haml

app/views/users/index.html.haml
= render 'nav_bar'
.row
	.small-6.columns
		- @users.each do |u|
			= u.name
			%br
			= u.email

		%br

app/views/users/new.html.haml
.row
	.small-6.small-centered.columns
		= form_for @new_user do |u|
			= u.label :name
			= u.text_field :name
	
		
			= u.label :email
			= u.text_field :email
	
		
			= u.label :password
			= u.password_field :password
	
		
			= u.label "password confirmation"
			= u.password_field :password_confirmation
	
			= u.submit "Sign up!"
.row
	= link_to "Go back", "/"

app/views/users/show.html.haml
= render 'nav_bar'
.row
	.small-4.columns
		= @user.name
		= @user.email

app/views/welcome/index.html.haml
.row
	.small-12.columns
		= image_tag('flying_spaghetti.jpg')
		.overlay
			.row
				.small-6.small-centered.columns
					.modal
						= form_tag sessions_path do
							.row
								.small-11.columns
								.small-1.columns
									%a.close-reveal-modal ×
							.row
								.small-9.small-centered.columns
									= label_tag :email, nil
									= text_field_tag :email, params[:email]
									%br

									= label_tag :password, nil
									= password_field_tag :password, nil
									%br
									= submit_tag "Login"
.row
	.small-7.columns
		%h1
			Welcome to the church of the 
	.small-5.columns.fsm
		%h1
			Flying Spaghetti Monster!
.row		
	.small-9.small-centered.columns		
		%h5 If you're new here, Please register and bask in the glory of his noodleness
.row

	.small-2.columns		 
		%a.button.signup{href: new_user_path} SignUp!
	.small-2.columns
		#login.button Login!
	.small-6.columns.end
		%p.ps p.s. click on the "Flying Spaghetti Monster" words
		